# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='utd.proto',
  package='hackutd',
  syntax='proto3',
  serialized_options=_b('\n\022io.hackutd.recycleB\007RecycleP\001\242\002\003HLW'),
  serialized_pb=_b('\n\tutd.proto\x12\x07hackutd\"\x19\n\x06Status\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t28\n\x07recycle\x12-\n\x08TestEcho\x12\x0f.hackutd.Status\x1a\x0e.hackutd.Reply\"\x00\x42%\n\x12io.hackutd.recycleB\x07RecycleP\x01\xa2\x02\x03HLWb\x06proto3')
)




_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='hackutd.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='hackutd.Status.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=47,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='hackutd.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='hackutd.Reply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'utd_pb2'
  # @@protoc_insertion_point(class_scope:hackutd.Status)
  ))
_sym_db.RegisterMessage(Status)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'utd_pb2'
  # @@protoc_insertion_point(class_scope:hackutd.Reply)
  ))
_sym_db.RegisterMessage(Reply)


DESCRIPTOR._options = None

_RECYCLE = _descriptor.ServiceDescriptor(
  name='recycle',
  full_name='hackutd.recycle',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=75,
  serialized_end=131,
  methods=[
  _descriptor.MethodDescriptor(
    name='TestEcho',
    full_name='hackutd.recycle.TestEcho',
    index=0,
    containing_service=None,
    input_type=_STATUS,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECYCLE)

DESCRIPTOR.services_by_name['recycle'] = _RECYCLE

# @@protoc_insertion_point(module_scope)
