# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackUTD' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftGRPC'
  pod 'SwiftProtobuf', '~> 1.0'

  # Pods for HackUTD

  target 'HackUTDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HackUTDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
